import 'package:flutter/material.dart';

class AsmaulHusna extends StatelessWidget {
  List<String> asmaulHusna = [
    "الرحمن	\n Yang Maha Pengasih",
    "الرحيم	\n Yang Maha Penyayang",
    "الملك	\n Yang Maha Merajai",
    "القدوس	\n Yang Maha Suci",
    "السلام	\n Yang Maha Memberi Kesejahteraan",
    "المؤمن	\n Yang Maha Memberi Keamanan",
    "المهيمن	\n Yang Maha Mengatur",
    "العزيز	\n Yang Maha Perkasa",
    "الجبار	\nYang Memiliki Mutlak Kegagahan",
    "المتكبر	\nYang Maha Megah",
    "الخالق	\nYang Maha Pencipta",
    "البارئ	\nYang Maha Melepaskan",
    "المصور	\nYang Maha Membentuk Rupa",
    "الغفار	\nYang Maha Pengampun",
    "القهار	\nYang Maha Memaksa",
    "الوهاب	\nYang Maha Pemberi Karunia",
    "الرزاق	\nYang Maha Pemberi Rezeki",
    "الفتاح	\nYang Maha Pembuka Rahmat",
    "العليم	\nYang Maha Mengetahui",
    "القابض	\nYang Maha Menyempitkan",
    "الباسط	\nYang Maha Melapangkan",
    "الخافض	\nYang Maha Merendahkan",
    "الرافع	\nYang Maha Meninggikan",
    "المعز	\nYang Maha Memuliakan",
    "المذل	\nYang Maha Menghinakan",
    "السميع	\nYang Maha Mendengar",
    "البصير	\nYang Maha Melihat",
    "الحكم	\nYang Maha Menetapkan",
    "العدل	\nYang Maha Adil",
    "اللطيف	\nYang Maha Lembut",
    "الحليم	\nYang Maha Penyantun",
    "العظيم	\nYang Maha Agung",
    "الغفور	\nYang Maha Memberi Pengampunan",
    "الشكور	\nYang Maha Pembalas Budi",
    "العلى	\nYang Maha Tinggi",
    "الكبير	\nYang Maha Besar",
    "الحفيظ	\nYang Maha Memelihara",
    "المقيت	\nYang Maha Pemberi Kecukupan",
    "الحسيب	\nYang Maha Membuat Perhitungan",
    "الجليل	\nYang Maha Luhur",
    "الكريم	\nYang Maha Pemurah",
    "الرقيب	\nYang Maha Mengawasi",
    "المجيب	\nYang Maha Mengabulkan",
    "الواسع	\nYang Maha Luas",
    "الحكيم	\nYang Maha Maka Bijaksana",
    "الودود	\nYang Maha Mengasihi",
    "المجيد	\nYang Maha Mulia",
    "الباعث	\nYang Maha Membangkitkan",
    "الشهيد	\nYang Maha Menyaksikan",
    "الحق	\nYang Maha Benar",
    "الوكيل	\nYang Maha Memelihara",
    "القوى	\nYang Maha Kuat",
    "المتين	\nYang Maha Kokoh",
    "الولى	\nYang Maha Melindungi",
    "الحميد	\nYang Maha Terpuji",
    "المحصى	\nYang Maha Menghitung",
    "المبدئ	\nYang Maha Memulai",
    "المعيد	\nYang Maha Mengembalikan Kehidupan",
    "المحيى	\nYang Maha Menghidupkan",
    "المميت	\nYang Maha Mematikan",
    "الحي	\nYang Maha Hidup",
    "القيوم	\nYang Maha Mandiri",
    "الواجد	\nYang Maha Penemu",
    "الماجد	\nYang Maha Mulia",
    "الواحد	\nYang Maha Tunggal",
    "الاحد	\nYang Maha Esa",
    "الصمد	\nYang Maha Dibutuhkan",
    "القادر	\nYang Maha Menentukan",
    "المقتدر	\nYang Maha Berkuasa",
    "المقدم	\nYang Maha Mendahulukan",
    "المؤخر	\nYang Maha Mengakhirkan",
    "الأول	\nYang Maha Awal",
    "الأخر	\nYang Maha Akhir",
    "الظاهر	\nYang Maha Nyata",
    "الباطن	\nYang Maha Ghaib",
    "الوالي	\nYang Maha Memerintah",
    "المتعالي	\nYang Maha Tinggi",
    "البر	\nYang Maha Penderma",
    "التواب	\nYang Maha Penerima Tobat",
    "المنتقم	\nYang Maha Pemberi Balasan",
    "العفو	\nYang Maha Pemaaf",
    "الرؤوف	\nYang Maha Pengasuh",
    "مالك الملك	\nYang Maha Penguasa Kerajaan",
    "ذو الجلال و الإكرام	\nYang Maha Pemilik Kebesaran dan Kemuliaan",
    "المقسط	\nYang Maha Pemberi Keadilan",
    "الجامع	\nYang Maha Mengumpulkan",
    "الغنى	\nYang Maha Kaya",
    "المغنى	\nYang Maha Pemberi Kekayaan",
    "المانع	\nYang Maha Mencegah",
    "الضار	\nYang Maha Penimpa Kemudharatan",
    "النافع	\nYang Maha Memberi Manfaat",
    "النور	\nYang Maha Bercahaya",
    "الهادئ	\nYang Maha Pemberi Petunjuk",
    "البديع	\nYang Maha Pencipta",
    "الباقي	\nYang Maha Kekal",
    "الوارث	\nYang Maha Pewaris",
    "الرشيد	\nYang Maha Pandai",
    "الصبور	\nYang Maha Sabar",
  ];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.green,
        title: Text("Asmaul Husna"),
      ),
      backgroundColor: Color(0xffe3e0ca),
      body: Container(
        child: ListView.builder(
            itemCount: asmaulHusna.length,
            itemBuilder: (context, index) {
          return Card(
            margin: EdgeInsets.all(5),
            color: Colors.white,
            child: Container(
              margin: EdgeInsets.all(6),
              child: Text(asmaulHusna[index]),
            ),
          );
        })
      ),
    );
  }
}
